### Should succeed - Create user "kienboec"
POST http://localhost:10001/users
Content-Type: application/json

{
  "Username": "kienboec",
  "Password": "daniel"
}
###

### Should succeed - Create user "altenhof"
POST http://localhost:10001/users
Content-Type: application/json

{
  "Username": "altenhof",
  "Password": "markus"
}

###

### Should fail - User already exists with the same password
POST http://localhost:10001/users
Content-Type: application/json

{
  "Username": "kienboec",
  "Password": "daniel"
}


###

### Should fail - User already exists with a different password
POST http://localhost:10001/users
Content-Type: application/json

{
  "Username": "kienboec",
  "Password": "different"
}
### 2) Login Users

### Login user "kienboec"
POST http://localhost:10001/sessions
Content-Type: application/json

{
  "Username": "kienboec",
  "Password": "daniel"
}
###
### Login user "altenhof"
POST http://localhost:10001/sessions
Content-Type: application/json

{
  "Username": "altenhof",
  "Password": "markus"
}
### Create Packages
POST http://localhost:10001/packages
Authorization: Bearer 87MN8WYYvKICVYMSVvGl4Z0yu5uEOGUtdZv/LPf6q5E=
Content-Type: application/json

[
  "d0745641-dc12-4109-9d80-b2b818c4e274",
  "451e3d88-b989-440a-aca5-b3da73abab9b",
  "f61fac88-1ae6-4b57-9f54-136d3d9e3f3b",
  "5d0fbd63-42ad-4751-8818-493ab07672dc",
  "5d0fbd63-42ad-4751-8818-493ab07672dc"
]

### Parchrase Pakage for the user "kienboec"
POST http://localhost:10001/transactions/package
Authorization: Bearer 87MN8WYYvKICVYMSVvGl4Z0yu5uEOGUtdZv/LPf6q5E=

### Parchrase Pakage for the user "altenhof"
POST http://localhost:10001/transactions/package
Authorization: Bearer gHWw6/CqDOwIQuhnCUtev0D/x9kp9qgb5xuNKk/ShQc=

### Begin the Battle Matchmaking "kienboec"
POST http://localhost:10001/battles
Authorization: Bearer 87MN8WYYvKICVYMSVvGl4Z0yu5uEOGUtdZv/LPf6q5E=

### Battle "kienboec" with "altenhof"
POST http://localhost:10001/battles
Authorization: Bearer gHWw6/CqDOwIQuhnCUtev0D/x9kp9qgb5xuNKk/ShQc=


