### Should succeed - Create user "kienboec"
POST http://localhost:10001/users
Content-Type: application/json

{
  "Username": "kienboec",
  "Password": "daniel"
}
###

### Should succeed - Create user "altenhof"
POST http://localhost:10001/users
Content-Type: application/json

{
  "Username": "altenhof",
  "Password": "markus"
}

###

### Should fail - User already exists with the same password
POST http://localhost:10001/users
Content-Type: application/json

{
  "Username": "kienboec",
  "Password": "daniel"
}


###

### Should fail - User already exists with a different password
POST http://localhost:10001/users
Content-Type: application/json

{
  "Username": "kienboec",
  "Password": "different"
}
### 2) Login Users

### Login user "kienboec"
POST http://localhost:10001/sessions
Content-Type: application/json

{
  "Username": "kienboec",
  "Password": "daniel"
}
###
### Login user "altenhof"
POST http://localhost:10001/sessions
Content-Type: application/json

{
  "Username": "altenhof",
  "Password": "markus"
}
### Create Packages
POST http://localhost:10001/packages
Authorization: Bearer 87MN8WYYvKICVYMSVvGl4Z0yu5uEOGUtdZv/LPf6q5E=
Content-Type: application/json

[
  "be453d72-cf27-4321-8b3f-58d29ab53da7",
  "be453d72-cf27-4321-8b3f-58d29ab53da7",
  "92649e8c-e3c0-43b8-a462-d49628eafe4c",
  "92649e8c-e3c0-43b8-a462-d49628eafe4c",
  "e2616927-0908-4dbc-af32-74ba0cd1449a"
]

### Parchrase Pakage for the user "kienboec"
POST http://localhost:10001/transactions/package
Authorization: Bearer SRFRgZ5i+fPLNRvoGJt9ulYvDgeLH0mRr6X88SUupR4=

### Parchrase Pakage for the user "altenhof"
POST http://localhost:10001/transactions/package
Authorization: Bearer E/mbSMPESqu+Fjk6yCF4q0VFt36bcthtUkhX/a/dDNg=

### Begin the Battle Matchmaking "kienboec"
POST http://localhost:10001/battles
Authorization: Bearer 87MN8WYYvKICVYMSVvGl4Z0yu5uEOGUtdZv/LPf6q5E=

### Battle "kienboec" with "altenhof"
POST http://localhost:10001/battles
Authorization: Bearer gHWw6/CqDOwIQuhnCUtev0D/x9kp9qgb5xuNKk/ShQc=


